
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.2.0"
  name          = "global-load-balancer-frontend"
  project_id    = var.global-lb-frontend_project_id
  url_map_input = module.global-lb-backend.backend_service_info
}
module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "global-load-balancer-backend"
  project_id = var.global-lb-backend_project_id
  serverless_neg_backends = [{
    region          = module.frontend-service.location
    service_name    = module.frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}
module "frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.frontend-service_project_id
  location                      = var.frontend-service_location
  service_name                  = "web-tier-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = merge({"order_management_service_SERVICE_ENDPOINT" = module.order-management-service.service_uri}, {"user_management_service_SERVICE_ENDPOINT" = module.user-management-service.service_uri}, {"payment_processing_service_SERVICE_ENDPOINT" = module.payment-processing-service.service_uri}, {"recommendation_service_SERVICE_ENDPOINT" = module.recommendation-service.service_uri})}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "order-management-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.order-management-service_project_id
  location                      = var.order-management-service_location
  service_name                  = "ord-mgmt-api-svc"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = {"order_management_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.order-management-db.instance_connection_name, "order_management_db_CLOUD_SQL_DATABASE_HOST" = module.order-management-db.instance_first_ip_address, "order_management_db_CLOUD_SQL_DATABASE_NAME" = module.order-management-db.env_vars.CLOUD_SQL_DATABASE_NAME}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor", "roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "order-management-db" {
  source              = "github.com/terraform-google-modules/terraform-google-sql-db//modules/mysql?ref=v26.2.2"
  project_id          = var.order-management-db_project_id
  name                = "order-management-storage"
  edition             = "ENTERPRISE_PLUS"
  database_version    = "MYSQL_8_0"
  availability_type   = "REGIONAL"
  deletion_protection = false
  data_cache_enabled  = true
  iam_users = [{
    email = module.order-management-service.service_account_id.email
    id    = module.order-management-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  database_flags              = [{"name" = "cloudsql_iam_authentication", "value" = "on"}]
  backup_configuration = {
    binary_log_enabled = true
    enabled            = true
  }
}
module "order-processing-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.order-processing-service_project_id
  location                      = var.order-processing-service_location
  service_name                  = "ord-prcssing-svc"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/bigquery.dataEditor"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "user-management-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.user-management-service_project_id
  location                      = var.user-management-service_location
  service_name                  = "usr-mgmt-api-svc"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_vars" = {"user_management_db_CLOUD_SQL_DATABASE_HOST" = module.user-management-db.instance_first_ip_address, "user_management_db_CLOUD_SQL_DATABASE_NAME" = module.user-management-db.env_vars.CLOUD_SQL_DATABASE_NAME, "user_management_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.user-management-db.instance_connection_name}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor", "roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "user-management-db" {
  source              = "github.com/terraform-google-modules/terraform-google-sql-db//modules/mysql?ref=v26.2.2"
  project_id          = var.user-management-db_project_id
  name                = "user-management-storage"
  edition             = "ENTERPRISE_PLUS"
  database_version    = "MYSQL_8_0"
  availability_type   = "REGIONAL"
  deletion_protection = false
  data_cache_enabled  = true
  iam_users = [{
    email = module.user-management-service.service_account_id.email
    id    = module.user-management-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  database_flags              = [{"name" = "cloudsql_iam_authentication", "value" = "on"}]
  backup_configuration = {
    binary_log_enabled = true
    enabled            = true
  }
}
module "payment-processing-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.payment-processing-service_project_id
  location                      = var.payment-processing-service_location
  service_name                  = "pmnt-prcssing-api-svc"
  containers                    = [{"env_secret_vars" = {"payment_processing_secret_SECRET" = module.payment-processing-secret.env_vars.SECRET}, "env_vars" = {"payment_processing_db_CLOUD_SQL_DATABASE_NAME" = module.payment-processing-db.env_vars.CLOUD_SQL_DATABASE_NAME, "payment_processing_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.payment-processing-db.instance_connection_name, "payment_processing_db_CLOUD_SQL_DATABASE_HOST" = module.payment-processing-db.instance_first_ip_address}, "container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor", "roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker", "roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "payment-processing-db" {
  source              = "github.com/terraform-google-modules/terraform-google-sql-db//modules/mysql?ref=v26.2.2"
  project_id          = var.payment-processing-db_project_id
  name                = "payment-processing-storage"
  edition             = "ENTERPRISE_PLUS"
  database_version    = "MYSQL_8_0"
  availability_type   = "REGIONAL"
  deletion_protection = false
  data_cache_enabled  = true
  iam_users = [{
    email = module.payment-processing-service.service_account_id.email
    id    = module.payment-processing-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  database_flags              = [{"name" = "cloudsql_iam_authentication", "value" = "on"}]
  backup_configuration = {
    binary_log_enabled = true
    enabled            = true
  }
}
module "payment-processing-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = var.payment-processing-secret_project_id
  name        = "payment-processing-secret"
  secret_data = module.payment-processing-db.generated_user_password
}
module "recommendation-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.recommendation-service_project_id
  location                      = var.recommendation-service_location
  service_name                  = "rcmndtn-api-svc"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container", "env_secret_vars" = {"recommendation_secret_SECRET" = module.recommendation-secret.env_vars.SECRET}, "env_vars" = {"recommendation_db_CLOUD_SQL_DATABASE_HOST" = module.recommendation-db.instance_first_ip_address, "recommendation_db_CLOUD_SQL_DATABASE_NAME" = module.recommendation-db.env_vars.CLOUD_SQL_DATABASE_NAME, "recommendation_db_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.recommendation-db.instance_connection_name}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"], ["roles/secretmanager.secretAccessor", "roles/cloudsql.instanceUser", "roles/cloudsql.client"])
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "recommendation-db" {
  source              = "github.com/terraform-google-modules/terraform-google-sql-db//modules/mysql?ref=v26.2.2"
  project_id          = var.recommendation-db_project_id
  name                = "recommendation-storage"
  edition             = "ENTERPRISE_PLUS"
  database_version    = "MYSQL_8_0"
  availability_type   = "REGIONAL"
  deletion_protection = false
  data_cache_enabled  = true
  iam_users = [{
    email = module.recommendation-service.service_account_id.email
    id    = module.recommendation-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  database_flags              = [{"name" = "cloudsql_iam_authentication", "value" = "on"}]
  backup_configuration = {
    binary_log_enabled = true
    enabled            = true
  }
}
module "recommendation-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = var.recommendation-secret_project_id
  name        = "recommendation-secret"
  secret_data = module.recommendation-db.generated_user_password
}
module "notification-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.6"
  project_id                    = var.notification-service_project_id
  location                      = var.notification-service_location
  service_name                  = "notification-service"
  containers                    = [{"container_image" = "us-docker.pkg.dev/cloudrun/container/hello", "container_name" = "service-container"}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = ["roles/pubsub.publisher", "roles/pubsub.subscriber", "roles/run.invoker"]
  ingress                       = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat(module.global-lb-frontend.apphub_service_uri, module.global-lb-backend.apphub_service_uri, [module.frontend-service.apphub_service_uri], [module.order-management-service.apphub_service_uri], [module.order-management-db.apphub_service_uri], [module.order-processing-service.apphub_service_uri], [module.user-management-service.apphub_service_uri], [module.user-management-db.apphub_service_uri], [module.payment-processing-service.apphub_service_uri], [module.payment-processing-db.apphub_service_uri], [module.recommendation-service.apphub_service_uri], [module.recommendation-db.apphub_service_uri], [module.notification-service.apphub_service_uri])
  application_id = var.apphub_application_id
}
