
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ip
}
output "global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.global-lb-frontend.external_ipv6_address
}
output "global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_http
}
output "global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.global-lb-frontend.ip_address_internal_managed_https
}
output "frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service.service_uri
}
output "order-management-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.order-management-service.service_uri
}
output "order-processing-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.order-processing-service.service_uri
}
output "user-management-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.user-management-service.service_uri
}
output "payment-processing-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.payment-processing-service.service_uri
}
output "recommendation-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.recommendation-service.service_uri
}
output "notification-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.notification-service.service_uri
}
