
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "global-lb-frontend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "global-lb-backend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type = string
}
variable "frontend-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "frontend-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "order-management-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "order-management-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "order-management-db_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "order-processing-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "order-processing-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "user-management-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "user-management-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "user-management-db_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "payment-processing-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "payment-processing-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "payment-processing-db_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "payment-processing-secret_project_id" {
  description = "The project ID to manage the Secret Manager resources"
  type = string
}
variable "recommendation-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "recommendation-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "recommendation-db_project_id" {
  description = "The project ID to manage the Cloud SQL resources"
  type = string
}
variable "recommendation-secret_project_id" {
  description = "The project ID to manage the Secret Manager resources"
  type = string
}
variable "notification-service_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "notification-service_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
